---
author: Cybersecurity and Infrastructure Security Agency
branding:
  color: black
  icon: align-justify
description: Format Python 2 source code with black.
name: Blacken Python 2

runs:
  using: docker
  image: Dockerfile
